#!/bin/bash
#SBATCH --job-name=combine
#SBATCH --qos=cu_hpc
#SBATCH --partition=cpu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=12G

# Source the CMS environment
source /work/app/cms/cmsset_default.sh
function cmsset() {
  cd ~/binary/CMSSW_14_1_0_pre5/src && source /work/app/share_env/hepsw.sh && cmsenv && cd -
}
cmsset

LUMI=1
DATABASE_FILE="yields_database.txt"

if [ ! -f "$DATABASE_FILE" ]; then
    echo "Error: $DATABASE_FILE not found! Run the C++ macro first."
    exit 1
fi

echo "Reading yields from $DATABASE_FILE..."

# Read the 6 columns generated by C++
while read -r MASS SIG_YIELD ZHTATA_YIELD ZHWW_YIELD ZZTATA_YIELD ZWW4L_YIELD; do
    
    # Skip empty lines
    [ -z "$MASS" ] && continue
    
    echo "--------------------------------------------------------"
    echo "Processing Mass Point: ${MASS} GeV"
    echo "Yields -> Sig: $SIG_YIELD | ZHTaTa: $ZHTATA_YIELD | ZHWW: $ZHWW_YIELD | ZZTaTa: $ZZTATA_YIELD | ZWW4l: $ZWW4L_YIELD"
    
    this_dir="Combine_Mass_${MASS}"
    rm -rf ${this_dir}
    mkdir -p ${this_dir}
    cd ${this_dir}

    # Prepare Data Card
    cp ../Data_Card_Combine.dat .
    sed -i "s/XXXX/${SIG_YIELD}/g" Data_Card_Combine.dat
    sed -i "s/YYYY/${ZHTATA_YIELD}/g" Data_Card_Combine.dat
    sed -i "s/ZZZZ/${ZHWW_YIELD}/g" Data_Card_Combine.dat
    sed -i "s/AAAA/${ZZTATA_YIELD}/g" Data_Card_Combine.dat
    sed -i "s/BBBB/${ZWW4L_YIELD}/g" Data_Card_Combine.dat
    
    CARD="Data_Card_Combine_mh${MASS}.dat"
    mv Data_Card_Combine.dat ${CARD}

    # Create the workspace and run combine
    for quantile in -1 0.5 0.84 0.16 0.975 0.025; do
        if [ "$quantile" == "-1" ]; then
            echo "Calculating Observed Limit"
            combine -M HybridNew --LHCmode LHC-limits ${CARD} --verbose 1 --saveHybridResult -s ${LUMI} \
                    --saveToys -T 5000 --setParameters lumiscale=${LUMI} --mass ${MASS} &
        else
            echo "Calculating Expected Limit for quantile ${quantile}"
            combine -M HybridNew --LHCmode LHC-limits ${CARD} --verbose 1 --saveHybridResult -s ${LUMI} \
                    --expectedFromGrid $quantile --saveToys -T 5000 --setParameters lumiscale=${LUMI} \
                    --mass ${MASS} &
        fi
    done
    
    # Wait for the jobs of THIS mass point to finish before generating the next directory
    wait 
    cd ..
    
done < "$DATABASE_FILE"

echo "All combine jobs Completed."